### ISSUE TITLE
Type error : unsupported operand type(s) for *:  'Float' and 'decimal' 

### ISSUE THREAD

**Issue by rishabhjain4** [mapillary/map_matching#5]
I tested the code on one of my test data and have added my shapefile(road_network data) directly to the database inside postgres. I have also created the .txt file for long and lat values as mentioned. I get the following error. 

![new doc_1](https://cloud.githubusercontent.com/assets/17268701/18349840/b70fe4ba-75f0-11e6-8133-1cab418c6980.jpg)

after going through the map_matcher test code, i dint find any error in datatype
I have gone through all the library packages and also the postgres database to check the data type.
What i found was, 
error in line 63 in road_routing.py where the variable edge.cost is of decimal type,
and i could not locate the edge tuple from where it is taking its value.

has anyone else come across this issue?
does the data which  entered n the database table should be edited more?

I hope the image is clear

python map_matcher.py "Connection details" table_name 30 2000 < textfile

**Comment by ptpt** [comment]
Thanks for reporting. It seems that `psycopg2` converts float values to `decimal` type instead of builtin float type. The latest commit should fix it. Reopen if it doesn't.

Tao

**Comment by rishabhjain4** [comment]
Thanks alot , the Process works smoothly now....
