### ISSUE TITLE
Simple Query, about HMM Algorithm ?

### ISSUE THREAD

**Issue by rishabhjain4** [mapillary/map_matching#6]
I am a total newbie to the concept of Creating algorithms for map matching,
Just have a query, whether Hidden Markov Model(HMM) is being used in your Map matching algorithm,

Because , I have applied your map matching algorithm on both dense and sparse road network,
it does show lot of issues in dense area networks, but where as sparse network is concerned i have seen issues where a single point from GPS tracks matches to other edges whereas all its other track points matches correctly.

If HMM is being used here, that shouldn't be the case ... i guess?

please can you clear my thoughts about whether HMM is being used here?

**Comment by ptpt** [comment]
Yes it uses HMM.

Could you show me a screenshot of the issue? It might there is no path found to that point.

**Comment by rishabhjain4** [comment]
![map_matching](https://cloud.githubusercontent.com/assets/17268701/18822651/cc2a46d2-83cf-11e6-8dbf-8689de89303c.jpg)

Sorry for the delayed reply,
in the above case, there are 5 points which are matching the road at a single point,
above 3 points and the below 2 points are circled, I don't think that algorithm has matched wrongly, but if we are considering the matching of a point relative to other matched points before, then we can make changes in the algorithm, for adjusting the size cluster for a better matching.
correct me if i am wrong...?

And if you can provide me a link to a better understand the algorithm gong behind, it would be great help,

**Comment by ptpt** [comment]
Yes the U-turn is still possible to occur as some points are too close to the "wrong link", which has high emission probabilities but low transition probabilities.

Try either increase the parameter `sgima_z` or decrese the parameter `beta` https://github.com/mapillary/map_matching/blob/master/map_matching/map_matching.py#L23. Both will decrease weight on emission probability and increase weight on the transition probability.

**Comment by eufr** [comment]
I'm experiencing similar issues with some of my datasets. You can clearly see that some points are snapped to "wrong" edges, especially at junctions. I tried to tune both parameters sigma_z and beta, but I am not getting any useful results here, e.g.:

(Note: the red and blue lines represent gps and snapped points respectively)

**1. No tuning, standard values:**
DEFAULT_BETA = 10.0
DEFAULT_SIGMA_Z = 4.07

![screen shot 2016-09-29 at 23 53 50](https://cloud.githubusercontent.com/assets/22531991/18974121/7b5b8f52-86a1-11e6-8547-0fdd1bb8358d.png)

**2. Decrease beta:**
DEFAULT_BETA = 1.0
DEFAULT_SIGMA_Z = 4.07

![screen shot 2016-09-30 at 00 02 02](https://cloud.githubusercontent.com/assets/22531991/18974100/62030f62-86a1-11e6-96d7-3c3e09c7076c.png)

**3. Increase sigma:**
DEFAULT_BETA = 10.0
DEFAULT_SIGMA_Z = 1.0

![screen shot 2016-09-30 at 00 00 42](https://cloud.githubusercontent.com/assets/22531991/18974113/6e67a308-86a1-11e6-97e4-229d1f06a7ee.png)

I tried lots of different values for beta and sigma, but I am still not happy with the results. Anything else I could try to achieve better results?

Thanks!

**Comment by Inland2** [comment]
I extended the example data set and experienced the same problem: U turns when the gps positions are close to a side road. 
Changing Sigma_z did have some influence on the results, unfortunately not on the U-turns. 
I didn't see any influence on the results after changing beta. 

![sequence_in_berlin_matches](https://cloud.githubusercontent.com/assets/22908792/19483291/25b67ef6-9554-11e6-9742-9ed0ff52706c.png)

**Comment by ptpt** [comment]
Thanks for the input and sorry for the inconvenience. This is likely to be a bug. We will investigate it.

**Comment by dali5** [comment]
can you please upadate the map matching algorithm ?

**Comment by ptpt** [comment]
Hi folks, for the performance reason we have switched to https://github.com/valhalla/valhalla. The same map matching algorithm is applied in Valhalla but written in C++ with many tweaks and improvement.This repo is therefore inactive. I highly recommend to take a look at Valhalla instead.

Thanks all.
