### ISSUE TITLE
Unable to run this Module after cloning it in my Mac

### ISSUE THREAD

**Issue by amangarg27081991** [mapillary/map_matching#9]

**Comment by rishabhjain4** [comment]
Just check the path of shortest_path.py in "..../site-packages/map_matching" folder

**Comment by amangarg27081991** [comment]
Hello @rishabhjain4 , 

I tried to figure out the path (see below):

![screen shot 2017-09-17 at 21 08 40](https://user-images.githubusercontent.com/31574661/30524048-8d9816ca-9bec-11e7-8b64-40be5f004022.png)

What do you recommend now?
